crimeTypeArr = [
    "crime",
    "battery",
    "vandalism",
    "rape, forcible",
    "shoplifting",
    "theft-grand",
    "criminal threats",
    "burglary from vehicle",
    "arson",
    "vehicle stolen",
    "theft plain",
    "assault with deadly weapon, aggravated assault",
    "robbery",
    "brandish weapon",
    "burglary",
    "battery police",
    "oral copulation",
    "simple assault",
    "theft from motor vehicle",
    "theft of identity",
    "theft, person",
    "battery with sexual contact",
    "bike stolen",
    "trespassing",
    "theft from motor vehicle",
    "theft from motor vehicle",
    "throwing object at moving vehicle",
    "bunco, grand theft",
    "aggravated assault",
    "attempted robbery",
    "other assault",
    "bomb scare",
    "document forgery",
    "stolen felony",
    "crm against child",
    "sexual penetration",
    "violation of court order",
    "shots fired at inhabited dwelling",
    "burglary, attempted",
    "child abuse",
    "violation of restraining order",
    "letters, lewd",
    "shoplifting",
    "indecent exposure",
    "violation of temporary restraining order",
    "bunco, petty theft",
    "kidnapping",
    "resisting arrest",
    "discharge firearms",
    "embezzlement",
    "kidnapping",
    "lewd conduct",
    "defrauding innkeeper",
    "purse snatching",
    "stalking",
    "sodomy/sexual",
    "child neglect",
    "contempt of court",
    "bunco, attempt",
    "unlawful sex",
    "counterfeit",
    "human trafficking",
    "extortion",
    "theft plain",
    "rape, attempted",
    "shoplifting",
    "false imprisonment",
    "burglary from vehicle, attempted",
    "disturbing the peace",
    "failure to yield",
    "threatening phone calls/letters",
    "vehicle attempt stolen",
    "embezzlement, petty theft ($950 & under)",
    "unauthorized computer access",
    "credit cards, fraud use ($950 & under",
    "pickpocket",
    "dishonest employee",
    "theft from person",
    "shots fired at moving vehicle, train or aircraft",
    "child stealing",
    "prowler",
    "child annoying",
    "sex offender registrant out of compliance",
    "credit card fraud",
    "assault with deadly weapon on police officer",
    "criminal homicide",
    "child pornography",
    "lewd/lascivious acts with child",
    "peeping tom",
    "battery on a firefighter",
    "till tap",
    "pimping",
    "false police report",
    "petty theft",
    "pandering",
    "disrupt school",
    "conspiracy",
    "document worthless",
    "driving without owner consent",
    "reckless driving",
    "boat - stolen",
    "drunk roll",
    "document worthless",
    "grand theft / insurance fraud",
    "cruelty to animals",
    "pickpocket, attempt",
    "drugs, to a minor",
    "child abandonment",
    "theft, coin machine - petty ($950 & under)",
    "illegal dumping",
    "attempted stolen",
    "firearms restraining order",
    "weapons possession/bombing",
    "contributing",
    "dishonest employee",
    "bribery",
    "manslaughter, negligent",
    "grand theft",
    "replica firearms",
    "theft, coin machine",
    "purse snatching",
    "lynching",
    "till tap",
    "telephone property damage",
    "bestiality, crime against nature sexual assault with anim",
    "failure to disperse",
    "firearms emergency protective order",
    "incest (sexual acts between blood relatives)"
  ]